dist: bionic
language: cpp
addons:
  apt:
    sources:
    packages:
      - gcc-7
      - g++-7
      - cmake
      - libboost-thread-dev
      - libboost-graph-dev
      - libcgal-dev
script:
    - make CXX=${CXX}
    - ./dp_maching