language: cpp
addons:
  apt:
    sources:
      # For gcc >= 4.8
      - ubuntu-toolchain-r-test
      # For cmake >= 2.8.8 (for CMakePackageConfigHelpers)
      - kubuntu-backports
      - boost-latest
    packages:
      - g++-7.5
      - cmake
      - libboost-thread-dev
      - libboost-graph-dev
      - libcgal-dev
      - postgresql-server-dev-all
      - postgresql-common
script:
    - make CXX=${CXX}
    - ./main